## this is the first Lab

In [ ]:
a=3
M
b=4

a+b

a

c=44

my_list = [1, 3.14, True, "abc"]

my_list

your_list = [2, 4, "ad"]

your_list

my_list + your_list

list_1 = [1,2,3,4]

list_2 = [5,6,7,8]

list_1 + list_2

import numpy as np

array_1 = np.array(list_1)

array_2 = np.array(list_2)

array_1[0] = 77

array_1 + array_2

array_1,array_2

tuple_1 = (1,2,3)

tuple_1

type(tuple_1)



In [50]:
a=3
b=4.1
c="i'am Lee"
d = True

In [52]:
a,b,c,d

(3, 4.1, "i'am Lee", True)

In [53]:
range(5)

range(0, 5)

In [59]:
for n in range(5000):
    print(n*10)

0
10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990
1000
1010
1020
1030
1040
1050
1060
1070
1080
1090
1100
1110
1120
1130
1140
1150
1160
1170
1180
1190
1200
1210
1220
1230
1240
1250
1260
1270
1280
1290
1300
1310
1320
1330
1340
1350
1360
1370
1380
1390
1400
1410
1420
1430
1440
1450
1460
1470
1480
1490
1500
1510
1520
1530
1540
1550
1560
1570
1580
1590
1600
1610
1620
1630
1640
1650
1660
1670
1680
1690
1700
1710
1720
1730
1740
1750
1760
1770
1780
1790
1800
1810
1820
1830
1840
1850
1860
1870
1880
1890
1900
1910
1920
1930
1940
1950
1960
1970
1980
1990
2000
2010
2020
2030
2040
2050
2060
2070
2080
2090
2100
2110
2120
2130
2140
2150
2160
2170
2180
2190
2200
2210
2

20220
20230
20240
20250
20260
20270
20280
20290
20300
20310
20320
20330
20340
20350
20360
20370
20380
20390
20400
20410
20420
20430
20440
20450
20460
20470
20480
20490
20500
20510
20520
20530
20540
20550
20560
20570
20580
20590
20600
20610
20620
20630
20640
20650
20660
20670
20680
20690
20700
20710
20720
20730
20740
20750
20760
20770
20780
20790
20800
20810
20820
20830
20840
20850
20860
20870
20880
20890
20900
20910
20920
20930
20940
20950
20960
20970
20980
20990
21000
21010
21020
21030
21040
21050
21060
21070
21080
21090
21100
21110
21120
21130
21140
21150
21160
21170
21180
21190
21200
21210
21220
21230
21240
21250
21260
21270
21280
21290
21300
21310
21320
21330
21340
21350
21360
21370
21380
21390
21400
21410
21420
21430
21440
21450
21460
21470
21480
21490
21500
21510
21520
21530
21540
21550
21560
21570
21580
21590
21600
21610
21620
21630
21640
21650
21660
21670
21680
21690
21700
21710
21720
21730
21740
21750
21760
21770
21780
21790
21800
21810
21820
21830
21840
21850
21860
21870
2188

40210
40220
40230
40240
40250
40260
40270
40280
40290
40300
40310
40320
40330
40340
40350
40360
40370
40380
40390
40400
40410
40420
40430
40440
40450
40460
40470
40480
40490
40500
40510
40520
40530
40540
40550
40560
40570
40580
40590
40600
40610
40620
40630
40640
40650
40660
40670
40680
40690
40700
40710
40720
40730
40740
40750
40760
40770
40780
40790
40800
40810
40820
40830
40840
40850
40860
40870
40880
40890
40900
40910
40920
40930
40940
40950
40960
40970
40980
40990
41000
41010
41020
41030
41040
41050
41060
41070
41080
41090
41100
41110
41120
41130
41140
41150
41160
41170
41180
41190
41200
41210
41220
41230
41240
41250
41260
41270
41280
41290
41300
41310
41320
41330
41340
41350
41360
41370
41380
41390
41400
41410
41420
41430
41440
41450
41460
41470
41480
41490
41500
41510
41520
41530
41540
41550
41560
41570
41580
41590
41600
41610
41620
41630
41640
41650
41660
41670
41680
41690
41700
41710
41720
41730
41740
41750
41760
41770
41780
41790
41800
41810
41820
41830
41840
41850
41860
4187

In [71]:
def my_f(b,d,a=100,c=144):
    print(a,b,c,d)
    
my_f(1,2)

100 1 144 2


In [74]:
a = "my name is chang"
b = "hyeon"
c = a+'  '+b
c

'my name is chang  hyeon'

In [75]:
d=123
e = '123'
type(d), type(e)

(int, str)

In [76]:
a = [0,1,2,3,4,5]
b = [5,'girl',2+0j]

In [84]:
type(b)
b[0],b[1],b[-1],b[-2]


(5, 'girl', (2+0j), 'girl')

In [85]:
b[:3]

[5, 'girl', (2+0j)]

In [86]:
b[1:2]

['girl']

In [87]:
b[1:3]

['girl', (2+0j)]

In [89]:
a = range(0,10,2)
a

range(0, 10, 2)

In [96]:
for n in a:
    print(n)

0
2
4
6
8


In [100]:
for n in range(0,-10,-2):
    print(n)

0
-2
-4
-6
-8


# list

In [103]:
mylist = ['one', 'two', 'three','four','five']
mylist_len = len(my_list)
mylist_len

5

In [134]:
for i in range(0,mylist_len):
    print(mylist[i])

one
two
three
four
five


In [141]:
#lsit 와 array의 차이점
a1 = [1,2,3.4]
array_a1 = np.array(a1)
a1,array_a1 # array는 같은타입으로 모두 변환시킨다

([1, 2, 3.4], array([1. , 2. , 3.4]))

In [139]:
type(a1)

list

# tuble

In [108]:
c = (1,2,3,4,5)
c[4]

5

# multidimensional list

In [110]:
a = [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [111]:
type(a)

list

# array (numpy)

In [112]:
import numpy as np

In [113]:
array_a = np.array(a)

In [114]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [115]:
a[1][2]

6

In [116]:
array_a[1][2]

6

In [119]:
a[0],array_a[0]

([1, 2, 3], array([1, 2, 3]))

# list slicng

In [120]:
a

[[1, 2, 3], [4, 5, 6]]

In [124]:
array_a[1,2]

6

In [125]:
a[-2:]

[[1, 2, 3], [4, 5, 6]]

In [129]:
a[0][0],a[0][1]

(1, 2)

# 1-D array

In [130]:
import numpy as np

In [131]:
# arange array range
a = np.arange(10)

In [132]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [148]:
b = [0,1,2,3,4,5,6,7,8,9]
b

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [149]:
a[3:10], b[3:10]

(array([3, 4, 5, 6, 7, 8, 9]), [3, 4, 5, 6, 7, 8, 9])

In [151]:
a+a, b+b

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [152]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
a[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2-D array examples

In [160]:
data = np.array([[11,22,0],[44,55,1],[77,88,1]])
data

array([[11, 22,  0],
       [44, 55,  1],
       [77, 88,  1]])

In [163]:
X, y = data[:,:-1], data[:,-1]

In [166]:
X,y

(array([[11, 22],
        [44, 55],
        [77, 88]]), array([0, 1, 1]))

In [167]:
X,y,X[0]

(array([[11, 22],
        [44, 55],
        [77, 88]]), array([0, 1, 1]), array([11, 22]))

In [191]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [195]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [198]:
c = np.arange(6)
c

array([0, 1, 2, 3, 4, 5])

In [203]:
c = c.reshape(2,3)
c

array([[0, 1, 2],
       [3, 4, 5]])

In [212]:
b = np.array(b)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
b = b.reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## arrays can also be created by Numpy functions

In [169]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [170]:
np.linspace(0,10) #기본 50개 출력

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [174]:
np.logspace(1,3,3)

array([  10.,  100., 1000.])

In [177]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [178]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [179]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [185]:
a = np.linspace(-1,5,7)
a, a*2, a/2, a-10, np.sin(a)

(array([-1.,  0.,  1.,  2.,  3.,  4.,  5.]),
 array([-2.,  0.,  2.,  4.,  6.,  8., 10.]),
 array([-0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5]),
 array([-11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.]),
 array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
        -0.7568025 , -0.95892427]))

In [186]:
np.sign(a)

array([-1.,  0.,  1.,  1.,  1.,  1.,  1.])

In [187]:
# excercise : create x-y dataset of y = cos(x) vs. x over interval (-pi,+pi)
x = np.linspace(-3.14,+3.14,21)
y = np.cos(x)
x,y

(array([-3.14 , -2.826, -2.512, -2.198, -1.884, -1.57 , -1.256, -0.942,
        -0.628, -0.314,  0.   ,  0.314,  0.628,  0.942,  1.256,  1.57 ,
         1.884,  2.198,  2.512,  2.826,  3.14 ]),
 array([-9.99998732e-01, -9.50612598e-01, -8.08267427e-01, -5.86882949e-01,
        -3.08108031e-01,  7.96326711e-04,  3.09622813e-01,  5.88171730e-01,
         8.09204181e-01,  9.51105720e-01,  1.00000000e+00,  9.51105720e-01,
         8.09204181e-01,  5.88171730e-01,  3.09622813e-01,  7.96326711e-04,
        -3.08108031e-01, -5.86882949e-01, -8.08267427e-01, -9.50612598e-01,
        -9.99998732e-01]))

# Dictionary

In [242]:
room = {"Kim":"201", "Lee":"202", "hung":"203"}
room

{'Kim': '201', 'Lee': '202', 'hung': '203'}

In [246]:
room.keys(), room.values()

(dict_keys(['Kim', 'Lee', 'hung']), dict_values(['201', '202', '203']))

# random number generation

In [249]:
np.random.rand(10) # 0~1

array([0.62601692, 0.0271851 , 0.66580114, 0.67050026, 0.21681028,
       0.98016304, 0.19006615, 0.92098338, 0.64008612, 0.14203782])

In [250]:
np.random.randn(10) #mean = 0, sigma = 1

array([-0.07075356, -1.23114737,  0.6210442 ,  1.00965682,  2.8314192 ,
       -0.02473893,  0.61256374, -0.96658284, -1.05361433,  1.53481556])

In [253]:
a,b = 10,20
a,b

(10, 20)

In [255]:
(b-a)*np.random.rand(10) + a #10~20

array([14.34844681, 16.68266645, 17.84717361, 15.1204454 , 14.24161732,
       15.47087697, 14.33915111, 18.57778732, 12.63586191, 14.48342366])

In [256]:
#normal  mean = 15, sigma = 10
x0,sigma = 15,10
sigma*np.random.randn(20) + x0


array([20.47401405, 12.92393353, 23.66417272,  5.86567282,  7.41435285,
       23.47167102,  8.46783243, 22.32936942, 15.34135269, 33.15353982,
       13.98225105, 12.04242574,  9.58878313, 15.7686815 , 12.33724064,
       10.39948375, 14.18366373, 25.76301298,  5.81818809, 16.59548655])

In [265]:
np.random.randint(1,7,12)

array([6, 1, 1, 1, 4, 6, 4, 1, 3, 2, 5, 4])

## call by what?

In [268]:
#looks like call by value
def test(a):
    a = 2

In [270]:
a = 1
test(a)
a

1

In [271]:
# looks like call by refernce
def test2(a):
    a.append("World")

In [273]:
b = ["Hello"]
test2(b)
b

['Hello', 'World']

In [274]:
# call by object
a = 10
b=a
a+=100
a,b

(110, 10)

In [275]:
id(a), id(b)

(1371400576, 1371398976)

In [277]:
a = [1,2,3]
b=a
a+=[4,5,6]
a,b

([1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6])

In [278]:
id(a),id(b)

(59282776, 59282776)

In [279]:
!dir

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: 9E69-74DC

 C:\Users\HNU 디렉터리

2019-02-18  오후 04:15    <DIR>          .
2019-02-18  오후 04:15    <DIR>          ..
2018-12-20  오후 01:28    <DIR>          .idlerc
2019-02-18  오후 01:25    <DIR>          .ipynb_checkpoints
2019-02-18  오후 01:25    <DIR>          .ipython
2018-11-26  오후 04:43    <DIR>          .vscode
2014-07-09  오전 11:43                 0 agent.log
2018-09-07  오후 02:03    <DIR>          Contacts
2019-02-18  오전 11:34    <DIR>          Desktop
2018-11-22  오후 04:29    <DIR>          Documents
2019-02-18  오전 11:30    <DIR>          Downloads
2018-09-07  오후 02:03    <DIR>          Favorites
2018-08-21  오후 01:58    <DIR>          HDGW
2018-09-07  오후 02:03    <DIR>          Links
2018-09-07  오후 02:03    <DIR>          Music
2018-09-07  오후 02:03    <DIR>          Pictures
2018-09-07  오후 02:03    <DIR>          Saved Games
2018-09-07  오후 02:03    <DIR>          Searches
2019-02-18  오후 04:15           114,056 Untitled.ipynb
2018-09-07  오후 02:03    <

In [280]:
help(list)

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

# Pandas DataFrame

In [282]:
import pandas as pd
import numpy as np

In [299]:
n1 = np.random.randn(6)
n2 = n.reshape(2,3)
n1,n2

(array([-0.71454278,  1.7174122 ,  0.09164989, -1.05177314, -0.31960866,
         1.16000629]), array([[ 1.95778673,  1.00520865, -0.3857152 ],
        [-1.11198526,  0.25548753,  0.22170778]]))

In [302]:
s0 = pd.Series(n)
s0

0    1.957787
1    1.005209
2   -0.385715
3   -1.111985
4    0.255488
5    0.221708
dtype: float64

In [301]:
s1 = pd.Series(n, index = ['a','b','c','d','e','f'])
s1

a    1.957787
b    1.005209
c   -0.385715
d   -1.111985
e    0.255488
f    0.221708
dtype: float64

In [305]:
s2 = pd.DataFrame(n2,columns = ['w','x','y'])
s2

w         x         y
0  1.957787  1.005209 -0.385715
1 -1.111985  0.255488  0.221708

In [312]:
s3 = pd.DataFrame(n2,index = ['a','b'],columns = ['w','x','y'])
s3

w         x         y
a  1.957787  1.005209 -0.385715
b -1.111985  0.255488  0.221708

In [307]:
type(s1)

pandas.core.series.Series

In [308]:
type(s2)

pandas.core.frame.DataFrame

In [309]:
s1.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [313]:
s2.index, s2.columns

(RangeIndex(start=0, stop=2, step=1), Index(['w', 'x', 'y'], dtype='object'))

In [314]:
s1[0]

1.9577867341807615

In [319]:
s3

w         x         y
a  1.957787  1.005209 -0.385715
b -1.111985  0.255488  0.221708

In [323]:
s3.median()

w    0.422901
x    0.630348
y   -0.082004
dtype: float64

In [324]:
s3.mean()

w    0.422901
x    0.630348
y   -0.082004
dtype: float64

In [328]:
ss = s1[s1>s1.median()]
ss

a    1.957787
b    1.005209
e    0.255488
dtype: float64

In [329]:
s1

a    1.957787
b    1.005209
c   -0.385715
d   -1.111985
e    0.255488
f    0.221708
dtype: float64

In [333]:
s1[1:]

b    1.005209
c   -0.385715
d   -1.111985
e    0.255488
f    0.221708
dtype: float64

In [332]:
s1[:-1]

a    1.957787
b    1.005209
c   -0.385715
d   -1.111985
e    0.255488
dtype: float64

In [334]:
s1[1:] + s1[:-1]

a         NaN
b    2.010417
c   -0.771430
d   -2.223971
e    0.510975
f         NaN
dtype: float64

In [339]:
s = pd.Series(np.random.randn(5), name = 'Dummy')
s

0    0.674627
1   -1.606218
2   -1.093403
3    2.045064
4    0.766510
Name: Dummy, dtype: float64

In [343]:
s.name

'Dummy'

In [341]:
d = {'one':[1,2,3,4], 'two':[4,3,2,1]}
d

{'one': [1, 2, 3, 4], 'two': [4, 3, 2, 1]}

In [342]:
type(d)

dict

In [344]:
df = pd.DataFrame(d)
df

one  two
0    1    4
1    2    3
2    3    2
3    4    1

In [345]:
df['one']

0    1
1    2
2    3
3    4
Name: one, dtype: int64

In [346]:
type(df)

pandas.core.frame.DataFrame

In [347]:
df['three'] = df['one'] + df['two']
df

one  two  three
0    1    4      5
1    2    3      5
2    3    2      5
3    4    1      5