# linear regression

In [60]:
# 선형모델
# y = wx + b
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


n = 100
x = np.random.randn(100)
y = x*20 + 10   # w = 20, b =10
y = y + np.random.randn(n) * 10  # add noise

plt.figure(figsize=(5,5))
plt.scatter(x,y)

w = np.random.randn()   # w에 랜덤으로 점 하나 찍기 random initial choise
b = np.random.randn()   # b도 마찬가지

lr = 0.1   # leaning( or training ) rate
n_epoch = 300  # 횟수

for epoch in range(n_epoch):
    y_pred = w * x + b
    error = (((y_pred - y)**2).mean())
    if error < 0.1:
        break
    w = w - lr * ((y_pred-y)*x).mean()
    b = b - lr * ((y_pred-y)).mean()
    if epoch%10 ==0:
        print('epoch = ', epoch,', error = ', error, ', w = ', w, ', b = ', b)
    
print('--------')
print('epoch = ', epoch,', error = ', error, ', w = ', w, ', b = ', b)

xx = np.linspace(-3,3,100)
yy = w * xx + b
plt.plot(xx,yy,c= 'k')

epoch =  0 , error =  768.0045865216807 , w =  1.7560966346840408 , b =  1.8811786799001846
epoch =  10 , error =  175.0024856759006 , w =  15.149137870990518 , b =  8.10791286654843
epoch =  20 , error =  125.34963934012117 , w =  19.18919476963809 , b =  9.537112119218648
epoch =  30 , error =  121.00192345970359 , w =  20.4336978588788 , b =  9.809644879468806
epoch =  40 , error =  120.5923987635383 , w =  20.826692884965148 , b =  9.834371857319445
epoch =  50 , error =  120.54964632281741 , w =  20.954318964681814 , b =  9.82052201222423
epoch =  60 , error =  120.54462028614084 , w =  20.99702305607815 , b =  9.808298072804051
epoch =  70 , error =  120.54396099523645 , w =  21.011748083748373 , b =  9.801527848226097
epoch =  80 , error =  120.54386712681513 , w =  21.016972321818677 , b =  9.798291081474044
epoch =  90 , error =  120.54385304751189 , w =  21.018873776239033 , b =  9.796847945673086
epoch =  100 , error =  120.54385087207562 , w =  21.019581074475994 , b =  9.7

In [94]:
# y = w1 * x1 + w2 * x2 + b
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


n = 100
x1 = np.random.randn(100)
x2 = np.random.randn(100)
y = x1 * 30 + x2 * 40 + 50   # w1 = 30, w2 = 40, b = 50
y = y + np.random.randn(n) * 1  # add noise

w1 = np.random.randn()   # w에 랜덤으로 점 하나 찍기 random initial choise
w2 = np.random.randn()
b = np.random.randn()   # b도 마찬가지

lr = 1.3   # leaning( or training ) rate
n_epoch = 30  # 횟수

for epoch in range(n_epoch):
    y_pred = w1 * x1 + w2 * x2 + b
    error = (((y_pred - y)**2).mean())
    if error < 1:
        break
    w1 = w1 - lr * ((y_pred-y)*x1).mean()
    w2 = w2 - lr * ((y_pred-y)*x2).mean()
    b = b - lr * ((y_pred-y)).mean()
    if epoch % 1 == 0:
        print('epoch = ', epoch,', error = ', error, ', w1 = ', w1, ', w2 = ', w2, ', b = ', b)
    
print('-------------')
print('epoch = ', epoch,', error = ', error, ', w1 = ', w1, ', w2 = ', w2, ', b = ', b)
        

epoch =  0 , error =  4139.257977179529 , w1 =  23.523231111172354 , w2 =  50.72344293623735 , b =  54.21928036729479
epoch =  1 , error =  205.75815232927778 , w1 =  33.150154683593684 , w2 =  33.547603744537525 , b =  49.85123453486792
epoch =  2 , error =  61.6747495300266 , w1 =  28.67330454694358 , w2 =  43.8278376886995 , b =  49.802830961902465
epoch =  3 , error =  22.94209173747337 , w1 =  30.700811709312624 , w2 =  37.38354583934174 , b =  50.827782891614014
epoch =  4 , error =  9.770290628502892 , w1 =  29.730016522961183 , w2 =  41.49753580086479 , b =  49.76741942743011
epoch =  5 , error =  4.6290613580278785 , w1 =  30.22616335374679 , w2 =  38.8415039840727 , b =  50.61579280644669
epoch =  6 , error =  2.493189817043382 , w1 =  29.955723017856016 , w2 =  40.56822994069239 , b =  49.99890183111946
epoch =  7 , error =  1.5839098112800607 , w1 =  30.111639903503967 , w2 =  39.44088549505139 , b =  50.42755106056144
epoch =  8 , error =  1.1933060620074385 , w1 =  30.017

### function으로 쉽게 돌려보자

In [ ]:
#EX3) y = w1 * x1 + w2 * x2 + b (function call)
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline


n = 100
x1 = np.random.randn(100)
x2 = np.random.randn(100)
y = x1 * 30 + x2 * 40 + 50   # w1 = 30, w2 = 40, b = 50
y = y + np.random.randn(n) * 15  # add noise

In [100]:
X = pd.DataFrame(x1)
X[1] = x2

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X,y)

model.coef_ , model.intercept_

(array([30.05351659, 39.88667741]), 50.25361902840099)

#### 이제 새로운 데이터를 만들어 사용해보자

In [101]:
new_X = [1,3]  
model.predict([new_X])  # 30 * 1 + 40 * 3 + 50

array([199.96716785])

In [107]:
# test data
z = np.random.rand(100,2)
model.predict(z)

array([ 81.8150475 ,  98.82604454,  68.91403644,  82.08436518,
        65.16348807,  76.69266125,  90.71948717,  96.49457719,
        55.1573747 ,  68.59088999,  76.29475918,  93.07817928,
       105.1960218 ,  79.1587061 ,  81.62834401,  93.20937251,
        94.81055198,  91.76515627,  70.37589606,  66.49586233,
        66.73819092,  89.37645769, 106.05057331,  95.21641756,
        74.1684603 , 103.06732201,  98.69087358, 110.10929272,
        90.69442473,  95.43864097,  72.74007463,  86.59696536,
        84.9293664 , 102.32386948,  60.74840343,  68.42710771,
        90.98469821,  74.3307371 , 101.64768972,  81.26668797,
       117.23663576, 108.79772759,  83.82519372, 105.41646327,
        85.89170139,  82.029189  ,  87.2318215 ,  57.02619956,
        71.95026556,  59.61934559,  72.93636677,  84.0722701 ,
        87.9399307 ,  85.48041936,  89.02651497,  93.88621439,
        71.88493819,  55.17647283,  82.32660617,  83.54127177,
        83.14894842,  68.46560992,  84.89348297, 102.87